***
# NumPy

Author: Olatomiwa Bifarin. 

_Treat (read) as drafts_

**Notebook Content**

1. [Introducing NumPy](#1)
2. [Arrays](#2) <br>
    2.1 [Basic Functions](#2.1) <br>
    2.2 [Creating Arrays](#2.2)
3. [Maths and Stats Functions](#3)
4. [Broadcasting](#4)
5. [Indexing and Slicing](#5)
5. [Resources](#6)

## 1 | Introducing NumPy
<a id='1'></a>


NumPy is a inescapable package for scientific computing in python. You can think of it as a foundation for numerous python packages. It has N-dimensional array object, broadcating functions, linear algebra functionalities among several others. 

Most people typical import <mark>numpy</mark> as <mark>np</mark>, so let's do the same.

In [48]:
import numpy as np

## 2 | Arrays: Basic Functions
<a id='2'></a>

### 2.1 | Basic Functions
<a id='2.1'></a>

**<mark>array( )</mark> function**

In [49]:
new = np.array([4, 6, 7, 9, 10])
new

array([ 4,  6,  7,  9, 10])

In [50]:
newfl = np.array([[4.2, 6.3, 7.1, 9.2, 10.9], [4.2, 6.3, 7.1, 9.2, 10.9]])
newfl

array([[ 4.2,  6.3,  7.1,  9.2, 10.9],
       [ 4.2,  6.3,  7.1,  9.2, 10.9]])

**<mark>type( )</mark> function**

In [51]:
print (type(new))
print (type(newfl))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


**<mark>size</mark>** 

In [52]:
print (new.size)
print (newfl.size)

5
10


**<mark>shape</mark>** 

In [53]:
print (new.shape)
print (newfl.shape)

(5,)
(2, 5)


**<mark>ndim</mark>**

In [54]:
print (new.ndim)  # gives you the dimension of an array. 
print (newfl.ndim)

1
2


### 2.2 | Creating Arrays
<a id='2.2'></a>

**<mark>np.array</mark>**

Here, we use the **<mark>array( )</mark>** function as we have described above

In [55]:
np.array([[4, 6, 7, 9, 10], [4, 6, 7, 9, 10]])

array([[ 4,  6,  7,  9, 10],
       [ 4,  6,  7,  9, 10]])

**<mark>np.zeros</mark>**

Here is a 6 by 5 matrix composed of just zeros. 

In [82]:
a = np.zeros((6,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**<mark>np.ones</mark>**

Here is a 4 by 5 matrix composed of just ones. 

In [57]:
b = np.ones((8,12))
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**<mark>np.arange</mark>** <br>

In <mark>np.arange( )</mark>, you use something akin to the <mark>range( )</mark> function in python to generate matrices creatively. <br> 
Recall: <mark>range(start: stop: skip)</mark>

In [58]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(2, 10, 2) #recall start: stop: skip

array([2, 4, 6, 8])

**<mark>np.reshape</mark>** <br>

The <mark>reshape( )</mark> function could be used along with <mark>arange( )</mark> function to dictate the dimensions of your matrices. 

Take the following:   

In [60]:
np.arange(3, 11).reshape(2,4)

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

**<mark>np.linspace</mark>** <br>

<mark>np.linspace</mark> has the same functionalities as in <mark>np.arange</mark> with the exception that the last number specify, in this case, the number of elements you want from the split. 

Take again the following: 

In [61]:
np.linspace(2, 10, 2)

array([ 2., 10.])

In [62]:
np.linspace(2, 10, 3)

array([ 2.,  6., 10.])

**<mark>np.random</mark>** <br>

Generates random values

In [63]:
np.random.rand(7, 5)

array([[0.76846623, 0.38498577, 0.46366581, 0.98226532, 0.42141377],
       [0.66474174, 0.64160926, 0.97525672, 0.4424971 , 0.03909627],
       [0.78606536, 0.13055605, 0.4063725 , 0.17919952, 0.65560741],
       [0.07485779, 0.38939899, 0.48259097, 0.11456792, 0.66230893],
       [0.51424784, 0.94206088, 0.19385801, 0.61061649, 0.28899845],
       [0.30425637, 0.19797754, 0.41345153, 0.45223838, 0.84346423],
       [0.44681942, 0.82220791, 0.91400992, 0.56228042, 0.83600686]])

To get a guassian distribution for your matrix, use <mark>randn<mark>

In [64]:
np.random.randn(7, 5)

array([[-1.70709612, -0.67864588,  1.60634272, -2.62181914,  1.72566941],
       [-0.55737623, -0.19763409,  1.15229653, -2.29838107,  0.00729788],
       [ 0.36574079,  0.78659895,  0.26650662,  0.42900055, -0.83054534],
       [-0.03339655,  0.23906845, -0.1209147 ,  0.07943486, -0.27822652],
       [-2.07286269,  0.32877653,  0.31775628,  0.12292225,  2.3417536 ],
       [-0.21710932,  0.05537702, -1.96005599, -0.94256109, -0.84347217],
       [-1.30194559,  1.02027086, -0.76532117, -1.45110908,  0.3306404 ]])

## 3 | Maths and Stats Functions
<a id='3'></a>

<mark>Arithmetic operations</mark>

In [65]:
a = [[4,5,6,7], 
     [3,4,5,6]]
b = [[5,6,7,7], 
     [1,1,1,2]]

In [66]:
print ("a + b =", np.add(a,b))
print ("a - b =", np.subtract(a,b))
print ("a * b =", np.multiply(a,b))
print ("a / b =", np.divide(a,b))
print ("a % b =", np.remainder(a,b))
print ("a ** b =", np.power(a,b))

a + b = [[ 9 11 13 14]
 [ 4  5  6  8]]
a - b = [[-1 -1 -1  0]
 [ 2  3  4  4]]
a * b = [[20 30 42 49]
 [ 3  4  5 12]]
a / b = [[0.8        0.83333333 0.85714286 1.        ]
 [3.         4.         5.         3.        ]]
a % b = [[4 5 6 0]
 [0 0 0 0]]
a ** b = [[  1024  15625 279936 823543]
 [     3      4      5     36]]


Take the following array _X_

In [67]:
X = [4,5,6,3,2,3]

**<mark>np.mean</mark>** <br>

Calculates mean

In [68]:
np.mean(X)

3.8333333333333335

**<mark>np.var</mark>** <br>

Calculates Variance

In [69]:
np.var(X)

1.8055555555555556

**<mark>np.power</mark>** <br>

Calculates the nth power

In [70]:
np.power(X, 3)

array([ 64, 125, 216,  27,   8,  27])

**<mark>Trig Functions</mark>** <br>

In [71]:
print(np.cos(X))
print(np.tan(X))

[-0.65364362  0.28366219  0.96017029 -0.9899925  -0.41614684 -0.9899925 ]
[ 1.15782128 -3.38051501 -0.29100619 -0.14254654 -2.18503986 -0.14254654]


## 4 | Broadcasting
<a id='4'></a>

In [91]:
ones = np.ones((2,3)) # a 2 by 3 consisting on only ones. 
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [92]:
ones += 1
ones

array([[2., 2., 2.],
       [2., 2., 2.]])

Notice that Python was able to add a scalar 1 to all of the elements in martix <mark>ones</mark>. <br>
What happened here is what is called __broadcasting.__ The ability to replicate a low dimensional array to the same length as a higher dimensional array. Here is another example:

In [94]:
x = np.zeros((3,5))
y = np.array([2, 3, 4, 5, 6])
z = x+y
print(z)

[[2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]]


The reader should note the alignment of the number of column in <mark>x</mark>, and the length of <mark>y</mark>. 

## 5 | Indexing and Slicing
<a id='5'></a>

___Indexing___

Let's take the 2D array <mark>a</mark> as defined above:

In [72]:
a

[[4, 5, 6, 7], [3, 4, 5, 6]]

In [73]:
print ("The first row = ", a[0])

The first row =  [4, 5, 6, 7]


In [74]:
print ("The second row = ", a[1])

The second row =  [3, 4, 5, 6]


To index specific elements, the first index operator represent the row and the second operator the column

In [75]:
a[0][1]

5

In [76]:
a[1][3]

6

___Slicing___

Recall that: 

In [77]:
X

[4, 5, 6, 3, 2, 3]

Now take the following slicing operations

In [81]:
print(X)
print(X[:3])
print(X[1:4])
print(X[1:])
print(X[:-1])
print(X[-1])

[4, 5, 6, 3, 2, 3]
[4, 5, 6]
[5, 6, 3]
[5, 6, 3, 2, 3]
[4, 5, 6, 3, 2]
3


## 6 | Resources
<a id='6'></a>

Take what you have seen here as a tip of the iceberg. For more on NumPy, check the well documented __[reference page.](https://docs.scipy.org/doc/numpy/reference/index.html)__